services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  api:
    build: .
    container_name: node_api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
